###Program 1

In [50]:
class Employee:

    #Creation of a data member to count the number of Employees
    number_of_employee = 0

    #Creation of a constructor to initialize name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.number_of_employee += 1

#Creation of a function to average salary
def calculate_average_salary(employees):
    total_salary = sum(Employee.salary for Employee in employees)
    average_salary = total_salary / len(employees)
    return average_salary

#Creation of a Fulltime Employee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

#Creation of instances of Employee class
employees_list = [Employee("Vardhan", "Vardhan Family", 85630, "HR"),
                  Employee("Yash", "Yash Family", 65380, "Finance"),
                  Employee("Harsha", "Harsha Family", 59840, "Employee")]

#Creation of instances of Fulltime Employee class
fulltime_employee = FulltimeEmployee("Tejesh", "Tejesh Family", 70000, "IT")

#Calling their member functions.
average_salary_result = calculate_average_salary(employees_list)

print(f"Average Salary: ${average_salary_result}")

print(f"Total Employees: {Employee.number_of_employee}")

print(f"Fulltime Employee Department: {fulltime_employee.department}")



Average Salary: $70283.33333333333
Total Employees: 4
Fulltime Employee Department: IT


### Program 2

In [51]:
import numpy as num

random_vector = num.random.uniform(1, 20, 20)

Array = random_vector.reshape((4, 5))

max_values = num.max(Array, axis=1)

Array[Array == max_values[:, num.newaxis]] = 0

print(Array)

[[ 0.          7.54054475 12.29799591 15.61293773  5.6414571 ]
 [ 0.         16.91424738 12.94285499 10.32554921  4.42670642]
 [ 7.45681398  0.          8.43433253 10.41786005  9.90727289]
 [15.6119747  15.70994257 12.62920053  0.          3.21494568]]
